const labels={basic:['基本給','基本賃金'],gross:['支給合計','総支給額','総支給合計','支給総額','総支給','支給額合計'],deductions:['控除合計','控除総額','総控除額','控除額合計','総控除'],net:['振込支給額','差引支給額','差引支給','振込金額','振込額','銀行振込','振込支給','手取額','手取り額']};
const norm=s=>String(s).normalize('NFKC').replace(/[\s　]/g,'');
function amounts(s){return [...s.matchAll(/(?:[¥￥])?\d[\d,，.．]*(?:円)?/g)].filter(m=>/^\d+(?:[,，.．]+\d{3})*$/.test(m[0].replace(/[¥￥円]/g,''))).map(m=>({value:Number(m[0].replace(/[^0-9]/g,'')),index:m.index,end:m.index+m[0].length})).filter(x=>Number.isSafeInteger(x.value)&&x.value<=9999999999);}
export function extractAmounts(data){const output={};const rows=[];if(data.tsv){const lines=data.tsv.trim().split('\n').slice(1),groups=new Map();for(const line of lines){const a=line.split('\t');if(a[0]!=='5'||!a[11]?.trim())continue;const key=a.slice(1,5).join('-');if(!groups.has(key))groups.set(key,[]);groups.get(key).push({text:norm(a.slice(11).join('\t')),x:+a[6],y:+a[7],w:+a[8],h:+a[9]});}for(const words of groups.values()){words.sort((a,b)=>a.x-b.x);let text='',chars=[];for(const w of words){const previous=chars.at(-1);if(previous&&/[0-9,，.．]$/.test(text)&&/^[0-9]/.test(w.text)&&w.x-(previous.x+previous.w)>Math.max(w.h,previous.h)*.6){text+=' ';chars.push({x:previous.x+previous.w,y:w.y,w:1,h:w.h});}for(let i=0;i<w.text.length;i++)chars.push({x:w.x+w.w*i/w.text.length,y:w.y,w:w.w/w.text.length,h:w.h});text+=w.text;}rows.push({text,chars});}}
 const hits=[],nums=[];
 for(const row of rows){for(const [key,aliases] of Object.entries(labels)){for(const label of aliases){const index=row.text.indexOf(label);if(index>=0){const chars=row.chars.slice(index,index+label.length);hits.push({key,row,index,end:index+label.length,x:chars[0].x,right:chars.at(-1).x+chars.at(-1).w,y:Math.min(...chars.map(c=>c.y)),h:Math.max(...chars.map(c=>c.h))});break;}}}for(const n of amounts(row.text)){const chars=row.chars.slice(n.index,n.end);if(chars.length)nums.push({...n,row,x:chars[0].x,right:chars.at(-1).x+chars.at(-1).w,y:chars[0].y,h:chars[0].h});}}
 for(const hit of hits){const same=nums.filter(n=>n.row===hit.row&&n.index>=hit.end&&!hits.some(h=>h.row===hit.row&&h.index>hit.index&&h.index<n.index));if(same.length){output[hit.key]=same[0].value;continue;}const h=Math.max(hit.h,10),center=(hit.x+hit.right)/2;const below=nums.filter(n=>n.y>hit.y+h*.65&&n.y-hit.y<h*4&&Math.abs((n.x+n.right)/2-center)<Math.max(hit.right-hit.x,n.right-n.x)*.75).sort((a,b)=>(a.y-hit.y+Math.abs((a.x+a.right)/2-center))-(b.y-hit.y+Math.abs((b.x+b.right)/2-center)));if(below[0])output[hit.key]=below[0].value;}
 // Text fallback handles vertically stacked labels without reliable word coordinates.
 const textLines=String(data.text||'').split('\n').map(norm).filter(Boolean);for(let i=0;i<textLines.length;i++){const line=textLines[i];for(const [key,aliases] of Object.entries(labels)){if(output[key]!==undefined)continue;const label=aliases.find(x=>line.includes(x));if(!label)continue;let tail=line.slice(line.indexOf(label)+label.length);const nextLabel=Object.values(labels).flat().map(x=>tail.indexOf(x)).filter(x=>x>=0).sort((a,b)=>a-b)[0];if(nextLabel!==undefined)tail=tail.slice(0,nextLabel);let ns=amounts(tail);if(!ns.length&&nextLabel===undefined&&Object.values(labels).flat().filter(x=>line.includes(x)).length===1&&textLines[i+1]&&!/[基本支給控除振込]/.test(textLines[i+1]))ns=amounts(textLines[i+1]);if(ns.length)output[key]=ns[0].value;}}
 return output;
}
