'use strict';
(() => {
const $=id=>document.getElementById(id), keys=['basic','gross','deductions','net'], names=['基本給','支給合計','控除合計','振込支給額'];
let dbPromise, records=[], draftId=null, draftImage=null, selectedId=null, dirty=false, workToken=0, cancelWork=null, backupURL=null, saving=false;
const money=n=>Number(n).toLocaleString('ja-JP')+' 円';
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';$('notice').hidden=false;}
function openDB(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('husband-payslip-fresh-20260930',1);r.onupgradeneeded=()=>r.result.createObjectStore('records',{keyPath:'id'});r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result);};r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('保存場所を開けません。ほかのタブを閉じて再度お試しください。'));}).catch(e=>{dbPromise=null;throw e;});return dbPromise;}
async function all(){const db=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction('records','readonly'),r=t.objectStore('records').getAll();t.oncomplete=()=>resolve(r.result);t.onerror=()=>reject(t.error);});}
async function write(items,remove){const db=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction('records','readwrite'),s=t.objectStore('records');try{for(const item of items)s.put(item);if(remove)s.delete(remove);}catch(e){t.abort();reject(e);return;}t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||new Error('保存を中止しました'));});}
async function refresh(){records=(await all()).sort((a,b)=>b.month.localeCompare(a.month)||b.updatedAt.localeCompare(a.updatedAt));}
function confirmAction(title,text,button='続ける'){return new Promise(resolve=>{const d=$('confirmDialog');$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmOK').textContent=button;let done=false;const finish=v=>{if(done)return;done=true;d.close();resolve(v);};$('confirmOK').onclick=()=>finish(true);$('confirmCancel').onclick=()=>finish(false);d.oncancel=e=>{e.preventDefault();finish(false);};d.showModal();});}
function stop(){workToken++;if(cancelWork){cancelWork();cancelWork=null;}$('stopRead').hidden=true;}
async function show(id,force=false){if(!force&&dirty&&!$('editor').hidden){if(!await confirmAction('入力をやめますか？','保存していない内容は残りません。','入力をやめる'))return false;dirty=false;}if(id!=='editor')stop();document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==id);window.scrollTo(0,0);try{if(['history','detail','graph','backup'].includes(id))await refresh();if(id==='history')renderList();if(id==='detail')renderDetail();if(id==='graph'){try{const g=await import('./graph.js');g.renderChart($('chart'),records);}catch{$('chart').replaceChildren(el('p','グラフを表示できませんでした。明細は「過去の明細」から確認できます。','empty'));}}}catch{notice('記録を開けませんでした。端末の空き容量やブラウザの保存設定をご確認ください。',true);}return true;}
function resetEditor(record){stop();$('recordForm').reset();draftId=record?.id||null;draftImage=record?.image||null;const today=new Date();$('month').value=record?.month||`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`;keys.forEach(k=>$(k).value=record?record[k].toLocaleString('ja-JP'):'');$('memo').value=record?.memo||'';$('readStatus').textContent=record?'金額・年月・メモを編集して、保存し直せます。':'4つの金額を入力してください。';$('balanceHint').textContent='';preview();dirty=false;}
function preview(){const p=$('preview');p.hidden=!draftImage;if(draftImage)p.src=draftImage;else p.removeAttribute('src');}
async function begin(){if(!await show('editor'))return false;resetEditor();return true;}
async function choose(input){if(!await begin())return;$(input).value='';$(input).click();}
function renderList(){const target=$('recordList');target.replaceChildren();if(!records.length){target.append(el('p','まだ明細がありません。今月のお給料を記録してみましょう。','empty'));return;}for(const r of records){const b=el('button',undefined,'record');b.append(el('span',r.month.replace('-','年')+'月'),el('strong',money(r.net)),el('small','振込支給額 · 詳細を見る'));b.onclick=()=>{selectedId=r.id;show('detail');};target.append(b);}}
function renderDetail(){const r=records.find(r=>r.id===selectedId);if(!r){show('history',true);return;}const target=$('recordDetail');target.replaceChildren(el('h1',r.month.replace('-','年')+'月'));const dl=el('dl');keys.forEach((k,i)=>{const row=el('div');row.append(el('dt',names[i]),el('dd',money(r[k])));dl.append(row);});target.append(dl);if(r.memo)target.append(el('h2','今月の感想／メモ'),el('p',r.memo,'memo'));if(r.image){const img=el('img',undefined,'slip');img.src=r.image;img.alt='保存した給与明細';target.append(img);}else target.append(el('p','写真なしの記録です。','hint'));}
function parseAmount(v){const s=String(v).normalize('NFKC').replace(/[,，\s￥¥円]/g,'');if(!/^\d{1,10}$/.test(s))return null;const n=Number(s);return Number.isSafeInteger(n)&&n<=9999999999?n:null;}
function getForm(){const r={id:draftId||crypto.randomUUID(),month:$('month').value,memo:$('memo').value.trim(),image:draftImage,updatedAt:new Date().toISOString()};if(!validMonth(r.month))throw new Error('年月を正しく入力してください。');keys.forEach((k,i)=>{r[k]=parseAmount($(k).value);if(r[k]===null){$(k).focus();throw new Error(names[i]+'を0以上の整数で入力してください。');}});return r;}
function validMonth(s){return typeof s==='string'&&/^(19\d{2}|20\d{2}|21\d{2}|2200)-(0[1-9]|1[0-2])$/.test(s);}
function identity(r){return JSON.stringify([r.month,...keys.map(k=>r[k]),r.memo]);}
async function save(event){event.preventDefault();if(saving)return;saving=true;$('saveButton').disabled=true;try{const r=getForm();await refresh();if(records.some(x=>x.id!==r.id&&x.month===r.month)){if(!await confirmAction('同じ年月の明細があります','別の明細として追加しますか？元の明細はそのまま残ります。','別の明細として保存'))return;}stop();await write([r]);dirty=false;selectedId=r.id;await show('detail',true);notice('💰 保存しました。今月もおつかれさま！');}catch(e){notice(e.name==='QuotaExceededError'?'空き容量が足りません。保存はできていません。バックアップ後に端末の空き容量を増やしてください。':e.message||'保存できませんでした。入力内容を残しています。',true);}finally{saving=false;$('saveButton').disabled=false;}}
async function readFile(file){if(!file)return;stop();const token=workToken;dirty=true;$('readStatus').textContent='写真を準備しています。手入力はいつでもできます。';$('stopRead').hidden=false;const touched=new Set();const mark=e=>touched.add(e.target.id);$('recordForm').addEventListener('input',mark);try{const mod=await import('./reader.js');if(token!==workToken)return;const controller=new AbortController();cancelWork=()=>controller.abort();const prepared=await mod.prepareImage(file,controller.signal);if(token!==workToken)return;draftImage=typeof prepared==='string'?prepared:prepared.storedImage;preview();$('readStatus').textContent='小さい文字や表の配置も含めて読み取っています。初回は少し時間がかかります。';const ocrImage=typeof prepared==='string'?prepared:prepared.ocrImage;const values=await mod.recognize(ocrImage,controller.signal,text=>{if(token===workToken)$('readStatus').textContent=text;});if(token!==workToken)return;let found=0;keys.forEach(k=>{if(values[k]!==undefined&&!touched.has(k)){$(k).value=values[k].toLocaleString('ja-JP');found++;}});$('readStatus').textContent=found?`${found}項目を読み取りました。写真と見比べて、必ず金額を確認してください。`:'金額を見つけられませんでした。写真を見ながら手入力できます。';balance();}catch(e){if(token===workToken)$('readStatus').textContent=draftImage?'自動で読み取れませんでした。写真は使えます。4つの金額を手入力してください。':'この写真を開けませんでした。別の写真（JPEGなど）を選ぶか、写真なしで手入力できます。';}finally{$('recordForm').removeEventListener('input',mark);if(token===workToken){cancelWork=null;$('stopRead').hidden=true;}}}
function balance(){const a=parseAmount($('gross').value),b=parseAmount($('deductions').value),c=parseAmount($('net').value);$('balanceHint').textContent=a!==null&&b!==null&&c!==null&&a-b!==c?'支給合計 − 控除合計と、振込支給額が異なります。現金支給などの場合もあります。写真と見比べて確認してください。':'';}
function validateBackup(obj){if(!obj||obj.app!=='husband-payslip-fresh'||obj.version!==1||!Array.isArray(obj.records)||obj.records.length>10000)throw new Error('このアプリのバックアップではありません。');return obj.records.map(r=>{if(!r||!validMonth(r.month)||typeof r.memo!=='string'||r.memo.length>3000||keys.some(k=>!Number.isSafeInteger(r[k])||r[k]<0||r[k]>9999999999)||!(r.image===null||(typeof r.image==='string'&&r.image.length<=12000000&&/^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/.test(r.image))))throw new Error('バックアップの内容が正しくありません。元の記録は変更していません。');return {id:crypto.randomUUID(),month:r.month,...Object.fromEntries(keys.map(k=>[k,r[k]])),memo:r.memo,image:r.image,updatedAt:new Date().toISOString()};});}
async function exportBackup(){try{await refresh();const blob=new Blob([JSON.stringify({app:'husband-payslip-fresh',version:1,exportedAt:new Date().toISOString(),records})],{type:'application/json'});if(backupURL)URL.revokeObjectURL(backupURL);backupURL=URL.createObjectURL(blob);const a=$('downloadAgain');a.href=backupURL;a.download=`お給料明細バックアップ-${new Date().toISOString().slice(0,10)}.json`;a.hidden=false;a.click();notice('バックアップを作成しました。表示された保存先で、ファイルを保存してください。');}catch{notice('バックアップを作成できませんでした。元の記録はそのままです。',true);}}
async function restore(file){if(!file)return;try{if(file.size>150*1024*1024)throw new Error('ファイルが大きすぎます（150MBまで）。');const incoming=validateBackup(JSON.parse(await file.text()));await refresh();const seen=new Set(records.map(identity)), additions=[];for(const r of incoming){const key=identity(r);if(!seen.has(key)){seen.add(key);additions.push(r);}}const skipped=incoming.length-additions.length;if(!additions.length){notice(`追加する記録はありません。同じ内容の${skipped}件を除きました。`);return;}if(!await confirmAction('バックアップを復元しますか？',`${additions.length}件を追加します。同じ内容の${skipped}件は追加しません。今ある記録は残ります。`,'復元する'))return;
// Recheck duplicates inside one read/write transaction, including concurrent tabs.
const db=await openDB();let added=0;await new Promise((resolve,reject)=>{const t=db.transaction('records','readwrite'),s=t.objectStore('records'),q=s.getAll();q.onsuccess=()=>{const current=new Set(q.result.map(identity));for(const r of additions){const key=identity(r);if(!current.has(key)){s.add(r);current.add(key);added++;}}};t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});notice(`${added}件を復元しました。元の記録も残っています。`);}catch(e){notice(e instanceof SyntaxError?'ファイルを読み込めませんでした。元の記録は変更していません。':e.message||'復元できませんでした。元の記録は変更していません。',true);}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('brand').onclick=e=>{e.preventDefault();show('home');};$('manualButton').onclick=begin;$('cameraButton').onclick=()=>choose('cameraInput');$('photoButton').onclick=()=>choose('photoInput');$('replacePhoto').onclick=()=>{$('photoInput').value='';$('photoInput').click();};for(const id of ['cameraInput','photoInput'])$(id).onchange=e=>readFile(e.target.files[0]);$('stopRead').onclick=()=>{stop();$('readStatus').textContent='読み取りを中止しました。金額を手入力してください。';};$('recordForm').onsubmit=save;$('recordForm').oninput=()=>{dirty=true;balance();};keys.forEach(k=>$(k).onblur=()=>{const n=parseAmount($(k).value);if(n!==null)$(k).value=n.toLocaleString('ja-JP');});$('editButton').onclick=async()=>{const r=records.find(r=>r.id===selectedId);if(r){await show('editor',true);resetEditor(r);}};$('deleteButton').onclick=async()=>{if(await confirmAction('この明細を削除しますか？','この1件の金額・写真・メモを削除します。元に戻せません。','削除する'))try{await write([],selectedId);await show('history',true);notice('明細を1件削除しました。');}catch{notice('削除できませんでした。もう一度お試しください。',true);}};$('exportButton').onclick=exportBackup;$('importButton').onclick=()=>{$('backupInput').value='';$('backupInput').click();};$('backupInput').onchange=e=>{const file=e.target.files[0];e.target.value='';restore(file);};window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
})();
