function abortError(){return new DOMException('中止しました','AbortError');}
function isolated(kind,payload,signal,onProgress,timeout){return new Promise((resolve,reject)=>{
 if(signal.aborted){reject(abortError());return;}const frame=document.createElement('iframe');frame.hidden=true;frame.src=new URL(kind==='heic'?'./heic-frame.html':'./processing-frame.html',import.meta.url).href;frame.title='写真の端末内処理';const job=crypto.randomUUID();let finished=false;
 const cleanup=()=>{clearTimeout(timer);window.removeEventListener('message',message);signal.removeEventListener('abort',abort);frame.remove();};
 const finish=(error,value)=>{if(finished)return;finished=true;cleanup();error?reject(error):resolve(value);};
 const abort=()=>finish(abortError());const timer=setTimeout(()=>finish(new Error('処理が時間内に終わりませんでした')),timeout);
 function message(e){if(e.source!==frame.contentWindow||e.origin!==location.origin)return;const d=e.data;if(d?.type==='ready'){frame.contentWindow.postMessage({kind,payload,job},location.origin);return;}if(d?.job!==job)return;if(d.type==='progress')onProgress?.(d.text);if(d.type==='done')finish(null,d.value);if(d.type==='error')finish(new Error('写真を処理できませんでした'));}
 window.addEventListener('message',message);signal.addEventListener('abort',abort,{once:true});frame.onerror=()=>finish(new Error('読み込みに失敗しました'));document.body.append(frame);
 });}
function decode(blob,signal){return new Promise((resolve,reject)=>{if(signal.aborted){reject(abortError());return;}const img=new Image(),url=URL.createObjectURL(blob);const clean=()=>{clearTimeout(timer);URL.revokeObjectURL(url);signal.removeEventListener('abort',abort);img.onload=null;img.onerror=null;};const abort=()=>{clean();img.src='';reject(abortError());};const timer=setTimeout(()=>{clean();img.src='';reject(new Error('画像を開けません'));},12000);img.onload=()=>{clean();resolve(img);};img.onerror=()=>{clean();reject(new Error('非対応の画像'));};signal.addEventListener('abort',abort,{once:true});img.src=url;});}
function sizeOf(image){return {width:image.naturalWidth||image.width,height:image.naturalHeight||image.height};}
function imageDataURL(img,maxEdge,quality,minEdge=0){
 const {width,height}=sizeOf(img),longest=Math.max(width,height);const ratio=Math.min(maxEdge/longest,Math.max(1,minEdge/longest));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(width*ratio));c.height=Math.max(1,Math.round(height*ratio));const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,c.width,c.height);const result=c.toDataURL('image/jpeg',quality);c.width=c.height=1;return result;
}
function documentCrop(image){
 const {width,height}=sizeOf(image),scale=Math.min(1,520/Math.max(width,height));const sample=document.createElement('canvas');sample.width=Math.max(1,Math.round(width*scale));sample.height=Math.max(1,Math.round(height*scale));const context=sample.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0,sample.width,sample.height);const data=context.getImageData(0,0,sample.width,sample.height).data,rows=[];
 for(let y=0;y<sample.height;y++){let count=0,first=sample.width,last=0;for(let x=0;x<sample.width;x++){const i=(y*sample.width+x)*4,r=data[i],g=data[i+1],b=data[i+2],light=r*.299+g*.587+b*.114,chroma=Math.max(r,g,b)-Math.min(r,g,b);if(light>145&&b>r*.68&&b>g*.72&&chroma<105){count++;first=Math.min(first,x);last=Math.max(last,x);}}rows.push({y,count,first,last});}
 const useful=rows.filter(row=>row.count>sample.width*.34);let best=[],run=[];for(const row of useful){if(!run.length||row.y===run.at(-1).y+1)run.push(row);else{if(run.length>best.length)best=run;run=[row];}}if(run.length>best.length)best=run;if(best.length<sample.height*.2){sample.width=sample.height=1;return image;}
 const quantile=(values,q)=>values.sort((a,b)=>a-b)[Math.min(values.length-1,Math.floor(values.length*q))];const top=best[0].y,bottom=best.at(-1).y,left=quantile(best.map(row=>row.first),.18),right=quantile(best.map(row=>row.last),.82);const pad=Math.round(Math.max(sample.width,sample.height)*.018),x1=Math.max(0,left-pad),y1=Math.max(0,top-pad),x2=Math.min(sample.width-1,right+pad),y2=Math.min(sample.height-1,bottom+pad);const area=(x2-x1)*(y2-y1)/(sample.width*sample.height);if(area<.12||area>.94){sample.width=sample.height=1;return image;}
 const crop=document.createElement('canvas'),sourceX=Math.round(x1/scale),sourceY=Math.round(y1/scale),sourceW=Math.min(width-sourceX,Math.round((x2-x1)/scale)),sourceH=Math.min(height-sourceY,Math.round((y2-y1)/scale));crop.width=sourceW;crop.height=sourceH;crop.getContext('2d').drawImage(image,sourceX,sourceY,sourceW,sourceH,0,0,sourceW,sourceH);sample.width=sample.height=1;return crop;
}
export async function prepareImage(file,signal){
 if(file.size>50*1024*1024)throw new Error('画像が大きすぎます');let blob=file,img;
 try{img=await decode(blob,signal);}catch(e){if(signal.aborted)throw e;const header=new TextDecoder('latin1').decode(await file.slice(0,80).arrayBuffer());if(!/\.hei[cf]$/i.test(file.name)&&!/hei[cf]/i.test(file.type)&&!/ftyp(heic|heix|hevc|hevx|mif1|msf1)/.test(header))throw e;blob=await isolated('heic',file,signal,null,45000);img=await decode(blob,signal);}
 if(signal.aborted)throw abortError();if(!img.naturalWidth||!img.naturalHeight)throw new Error('空の画像');const ocrSource=documentCrop(img);const result={storedImage:imageDataURL(img,2200,.86),ocrImage:imageDataURL(ocrSource,3400,.94,2600)};if(ocrSource!==img)ocrSource.width=ocrSource.height=1;return result;
}
export async function recognize(image,signal,onProgress){const data=await isolated('ocr',image,signal,onProgress,210000);const {extractAmounts}=await import('./amounts.js');return extractAmounts(data);}
